Repository elastic/elasticsearch-sql-odbc, pull requests merged in 2019-07, with the labels that each got.

#161 Remove support for the frozen indices param
  driver/connect.c
  driver/defs.h
  driver/dsn.c
  driver/dsn.h
  driver/handles.h
  driver/queries.c
  driver/queries.h
  test/connected_dbc.cc
Labels: >bug, v7.2.1

#162 Add timing logging for the REST request
  driver/connect.c
  driver/handles.c
  driver/queries.c
Labels: >enhancement, v7.4.0, v8.0.0

#163 Fix time to timestamp conversion unit test
  test/test_conversion_c2sql_timestamp.cc
Labels: >test, v7.4.0, v8.0.0

#165 Logging: descriptors setting logged back on debug level
  driver/handles.c
Labels: >enhancement, v7.4.0, v8.0.0

#167 bump version 6.8.2 -> 6.8.3
  CMakeLists.txt
Labels: >non-issue

#166 bump version 7.2.1->7.2.2
  CMakeLists.txt
Labels: >non-issue, v7.2.1
