Repository elastic/elasticsearch-sql-odbc, pull requests merged in 2020-10, with the labels that each got.

#259 Bump version to 7.11
  CMakeLists.txt
Labels: >non-issue

#256 Log credentials used to set up a connection
  driver/connect.c
Labels: >bug, v7.10.0, v7.11.0, v8.0.0

#254 Properly redo looping on TS servers on signing
  installer/build/scripts/Build.fsx
Labels: >non-issue, v7.10.0, v7.11.0, v8.0.0

#260 Testing convenience: build testing DSN out of a provided ES URL
  test/integration/data.py
  test/integration/testing.py
Labels: >test, v7.11.0, v8.0.0

#249 Update CMake generation for Visual Studio 16
  README.md
  build.bat
Labels: >enhancement, v7.10.0, v8.0.0

#261 Retarget project to latest Windows SDK 10 version
  dsneditor/EsOdbcDsnBinding/EsOdbcDsnBinding.vcxproj
Labels: >non-issue, v7.10.0, v7.11.0, v8.0.0

#262 Bump version after 7.9.3 release
  CMakeLists.txt
Labels: >non-issue
