Repository elastic/elasticsearch-sql-odbc, pull requests merged in 2020-03, with the labels that each got.

#215 Prepare the driver to work with newer server releases than its own
  driver/connect.c
  driver/defs.h
  driver/dsn.c
  driver/dsn.h
  driver/handles.h
  driver/info.c
  driver/queries.c
  driver/queries.h
  test/connected_dbc.cc
  test/connected_dbc.h
Labels: >enhancement, v7.7.0, v8.0.0

#213 Allow some statement attributes be used for a connection
  driver/connect.c
Labels: >enhancement, v7.7.0, v8.0.0

#216 Switch to CBOR as default packing mode
  driver/queries.c
  driver/queries.h
  dsneditor/EsOdbcDsnEditor/DSNEditorForm.Designer.cs
  dsneditor/EsOdbcDsnEditor/DSNEditorForm.cs
  test/connected_dbc.cc
Labels: >enhancement, v7.6.2, v7.7.0, v8.0.0

#217 Fixes: possible buffer overrun on interval conversion. Catalog length handling
  driver/connect.c
  driver/convert.c
Labels: >bug, v6.8.8, v7.6.2, v7.7.0, v8.0.0

#224 Types: add support for constant_keyword type
  CMakeLists.txt
  driver/connect.c
  driver/connect.h
Labels: >enhancement, v7.7.0, v8.0.0

#225 Test: PR#217 complete.
  test/test_driverconnect.cc
Labels: >test, v6.8.8, v7.6.2, v7.7.0, v8.0.0

#223 Params: ignore unbound parameters
  driver/handles.c
  driver/handles.h
  driver/queries.c
  test/connected_dbc.cc
  test/test_bindparam.cc
Labels: >bug, v7.7.0, v8.0.0

#226 Fix: SQLGetData: only update offset if C-string data copied out
  driver/convert.c
  test/test_sqlgetdata.cc
Labels: >bug, v7.7.0, v8.0.0

#218 Update type selection for string parameters
  .gitignore
  build.bat
  driver/connect.c
  driver/defs.h
  driver/handles.c
  driver/handles.h
  driver/log.c
  driver/odbc.c
  driver/queries.c
  driver/util.c
  test/integration/install.py
  test/test_conversion_c2sql_varchar.cc
Labels: >enhancement, v7.7.0, v8.0.0

#227 Add an early execution mode for prepared statements
  driver/connect.c
  driver/defs.h
  driver/dsn.c
  driver/dsn.h
  driver/handles.c
  driver/handles.h
  driver/queries.c
Labels: >feature, v7.7.0, v8.0.0

#229 Introduce new varchar limitation option
  driver/catalogue.c
  driver/catalogue.h
  driver/connect.c
  driver/convert.c
  driver/defs.h
  driver/dsn.c
  driver/dsn.h
  driver/handles.h
  driver/queries.c
  driver/util.h
  test/integration/data.py
  test/integration/ites.py
  test/integration/testing.py
  test/test_catalogue.cc
  test/test_sqlgetdata.cc
Labels: >feature, v7.7.0, v8.0.0

#230 Bump 7.x to 7.8.0
  CMakeLists.txt
Labels: >non-issue

#232 Fix varchar type definition
  driver/connect.c
  driver/connect.h
  driver/convert.c
  driver/defs.h
  driver/queries.c
  test/connected_dbc.h
  test/test_queries.cc
Labels: >bug, v7.7.0, v7.8.0, v8.0.0

#233 Fix debug printing of SQL(U)LEN variables
  driver/connect.c
  driver/convert.c
  driver/handles.c
  driver/queries.c
  driver/tracing.h
Labels: >bug, v7.7.0, v7.8.0, v8.0.0

#231 Fix varchar limitation when max-len-attr is set
  driver/catalogue.c
  driver/convert.c
  driver/defs.h
  driver/dsn.c
  driver/dsn.h
  driver/handles.h
  driver/util.h
  test/test_catalogue.cc
  test/test_queries.cc
Labels: >bug, >non-issue, v7.7.0, v7.8.0, v8.0.0

#228 bump version to 6.8.9
  CMakeLists.txt
Labels: >non-issue, v6.8.8
