Repository elastic/elasticsearch-sql-odbc, pull requests merged in 2021-04, with the labels that each got.

#277 Update license definition
  LICENSE.rtf
  LICENSE.txt
Labels: >non-issue, v7.12.0, v7.13.0, v8.0.0

#276 Add connection proxying support
  driver/connect.c
  driver/defs.h
  driver/dsn.c
  driver/dsn.h
  driver/handles.h
  driver/odbc.c
  driver/util.c
  dsneditor/EsOdbcDsnEditor/DSNEditorForm.Designer.cs
  dsneditor/EsOdbcDsnEditor/DSNEditorForm.cs
Labels: >feature, v7.13.0, v8.0.0

#278 Bump version for 7.12.2
  CMakeLists.txt
Labels: v7.12.2
